import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import { useDebounce } from "use-debounce";
import Container from "../components/Container/Container";
import { useTogglerContext } from "../components/Context/TogglerContext";
import SearchContainer from "../components/Search/SearchContainer";
import Toggle from "../components/Toogles/Toggle";

export default function Home() {
  const { checked } = useTogglerContext();
  return (
    <>
      <Head>
        <title>Programming Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <h1>Programming Quotes</h1>
        <p>{checked?"Author":"Quotes"}</p><Toggle/>
        <SearchContainer />
      </Container>
    </>
  );
}
