import Head from "next/head";
import Link from "next/link";
import { StyledLink } from "../components/Author/Author.styles";
import Container from "../components/Container/Container";
import { useTogglerContext } from "../components/Context/TogglerContext";
import SearchContainer from "../components/Search/SearchContainer";
import Toggle from "../components/Toogles/Toggle";

export default function Home() {
  const { checked } = useTogglerContext();
  return (
    <>
      <Head>
        <title>Programming Quotes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <h1>Programming Quotes</h1>
        <Link href="/quotes/random">
          <StyledLink
            href="/quotes/random"
            style={{ position: "fixed", top: 10, right: 10 }}
          >
            Quote Random Generator
          </StyledLink>
        </Link>
        <p>{checked ? "Author" : "Quotes"}</p>
        <Toggle />
        <SearchContainer />
      </Container>
    </>
  );
}
